spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fishing_king
    username: root
    password: root123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jooq:
    sql-dialect: mysql